#ifndef MACROSTRINGS_H
#define MACROSTRINGS_H

#include <QObject>

#define STRING_TIP              QObject::tr("Tip")
#define STRING_OK               QObject::tr("Ok")
#define STRING_CANCEL           QObject::tr("Cancel")
#define STRING_INVALID          QObject::tr("Invalid")
#define STRING_FAILED           QObject::tr("failed")

#define STRING_UI_WINDOW_TITLE  QObject::tr("Vehicle detector simulator")
#define STRING_UI_EXISTS        QObject::tr("Already exists")
#define STRING_UI_ASSIGNED      QObject::tr("Already assigned to")
#define STRING_UI_OTHER         QObject::tr("Other")
#define STRING_UI_LANE          QObject::tr("lane")
#define STRING_UI_OPEN          QObject::tr("Open")
#define STRING_UI_CLOSE         QObject::tr("Close")
#define STRING_UI_SERIALPORT    QObject::tr("Serial port")
#define STRING_UI_EXISTS_INVALID_LANEID     QObject::tr("Exists invalid lane id")

#define STRING_UI_SEND          QObject::tr("Send msg")
#define STRING_UI_START         QObject::tr("Start")
#define STRING_UI_STOP          QObject::tr("Stop")
#define STRING_UI_TIMESPAN      QObject::tr("Departure interval")

#define STRING_UI_PORT          QObject::tr("Port")
#define STRING_UI_BAUDRATE      QObject::tr("Baud rate")
#define STRING_UI_DATABIT       QObject::tr("Data bit")
#define STRING_UI_PARITY        QObject::tr("Parity")
#define STRING_UI_STOPBIT       QObject::tr("Stop bit")

#define STRING_UI_GREEN_TIP     QObject::tr("Green arrow indicates come")
#define STRING_UI_RED_TIP       QObject::tr("Red arrow indicates left")

#define STRING_UI_SCHEDULE_ID       QObject::tr("Schedule id")
#define STRING_UI_EVENT_ID          QObject::tr("Event id")
#define STRING_UI_START_END_TIME    QObject::tr("Start and end time")
#define STRING_UI_CYCLE_TIME        QObject::tr("Cycle time")
#define STRING_UI_CTRL_MODE         QObject::tr("Ctrl mode")
#define STRING_UI_STAGE_ID          QObject::tr("Stage id")
#define STRING_UI_CURRENT_PHASE     QObject::tr("Current phase")
#define STRING_UI_PHASE_TIME        QObject::tr("Phase time")
#define STRING_UI_GYR_LIGHT         QObject::tr("Green-Yellow-Red")
#define STRING_UI_SIGNALER_TIME     QObject::tr("Signaler time")
#define STRING_UI_CONNECT           QObject::tr("Connect")
#define STRING_UI_DISCONNECT        QObject::tr("Disconnect")
#define STRING_UI_DETECTOR_EDIT     QObject::tr("Edit detector id")
#define STRING_UI_DETECTOR_ID_EDIT_TITLE    QObject::tr("Detector id edit window")

#define STRING_UI_EAST              QObject::tr("East")
#define STRING_UI_SOUTH             QObject::tr("South")
#define STRING_UI_WEST              QObject::tr("West")
#define STRING_UI_NORTH             QObject::tr("North")

//#define STRING_UI_LANE              QObject::tr("Lane")
#define STRING_UI_SIDEWALK          QObject::tr("Sidewalk")
#define STRING_UI_IP                QObject::tr("IP")

// SyncCommand
#define STRING_CONNECT_HOST_REFUSED     QObject::tr("Connected host refused")
#define STRING_CONNECT_HOST_CLOSED      QObject::tr("Remote host closed")
#define STRING_CONNECT_HOST_NOTFIND     QObject::tr("Host not found")
#define STRING_CONNECT_SOCK_ACCESS_ERR  QObject::tr("Socket access error")
#define STRING_CONNECT_SOCK_RESOURCE_E  QObject::tr("Socket resource error")
#define STRING_CONNECT_SOCK_TIMEOUT     QObject::tr("Socket timeout error")
#define STRING_CONNECT_DATA_TOO_LARGE   QObject::tr("Datagram is too large")
#define STRING_CONNECT_NETWORK_ERR      QObject::tr("Network error")
#define STRING_CONNECT_ADDRESS_INUSE    QObject::tr("Address is in use")
#define STRING_CONNECT_ADDR_NOT_ABLE    QObject::tr("Socket address not available")
#define STRING_CONNECT_UNSUPPORTED      QObject::tr("Unsupported socket operation")
#define STRING_CONNECT_UNFINISHED       QObject::tr("Unfinished socket operation")
#define STRING_CONNECT_PROXY_AUTH       QObject::tr("Proxy authentication required")
#define STRING_CONNECT_SSL_ERROR        QObject::tr("SSL handshake failed")
#define STRING_CONNECT_PROXY_REFUSED    QObject::tr("Proxy connection refused")
#define STRING_CONNECT_PROXY_CLOSED     QObject::tr("Proxy connection closed")
#define STRING_CONNECT_PROXY_TIMEOUT    QObject::tr("Proxy connection timeout")
#define STRING_CONNECT_PROXY_NOTFIND    QObject::tr("Proxy not found")
#define STRING_CONNECT_PROXY_PROTOCOL   QObject::tr("Proxy protocol error")
#define STRING_CONNECT_UNKNOWN          QObject::tr("Unknown error")

// Ctrl mode desc
#define STRING_CTRL_AUTONOMOUS          QObject::tr("Autonomous ctrl")
#define STRING_CTRL_CLOSE_LIGHT         QObject::tr("Close lights ctrl")
#define STRING_CTRL_YELLOW_FLASH        QObject::tr("Yellow flash ctrl")
#define STRING_CTRL_ALL_RED             QObject::tr("All red ctrl")
#define STRING_CTRL_COORDINATE          QObject::tr("Coordinate ctrl")
#define STRING_CTRL_FULL_INDUCTION      QObject::tr("Full induction ctrl")
#define STRING_CTRL_MAIN_HALF_INDUCTION QObject::tr("Main road half induction ctrl")
#define STRING_CTRL_SECOND_HALF_INDUC   QObject::tr("Secondary road half induction ctrl")
#define STRING_CTRL_SINGLE_ADAPT        QObject::tr("Single point adapt ctrl")
#define STRING_CTRL_CROSS_STREET        QObject::tr("Pedestrian crossing")
#define STRING_CTRL_COOR_INDUCTION      QObject::tr("Coordinate induction")
#define STRING_CTRL_BUS_FIRST           QObject::tr("Bus first")
#define STRING_CTRL_TRAFFIC_CTRL        QObject::tr("Traffic control")
#define STRING_CTRL_MANUAL_CTRL         QObject::tr("Manual control")
#define STRING_CTRL_SYS_FAULT_YELLOW    QObject::tr("System fault cause to yellow flash")


#endif // MACROSTRINGS_H
